# Generated by Django 3.0.4 on 2020-03-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='joke',
            new_name='text',
        ),
    ]
